version: "3.1"
services:

  supspace-client:
    build:
      context: ../supspace-client
      dockerfile: Dockerfile.client.dev
    container_name: supspace-client
    restart: unless-stopped
    image: supspace-client
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SOCKET=http://localhost:8091
      - NEXT_PUBLIC_API=http://localhost:8091/api/v1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    # environment:
    #   NODE_ENV: developmentdoc
    networks:
      - supspace-network
    stdin_open: true
    tty: true
    depends_on:
      - supspace-api

  supspace-api:
    build: 
      context: ../supspace-api
      dockerfile: Dockerfile.api.dev
    container_name: supspace-api
    restart: unless-stopped
    image: supspace-api
    environment:
      ONGODB_URI: mongodb://mongo:supspace1@mongodb:27017/
      MONGODB_DB_NAME: supspace-api-dev
      JWT_SECRET: edam1234
      JWT_EXPIRE: 30d
      SMTP_USERNAME: supchat24@outlook.com
      SMTP_PASSWORD: cin11149398
      NODE_ENV: development
      GOOGLE_CLIENT_ID: smth.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: SMTH-SMTH
      CLIENT_URL: http://supspace-client:3000
      API_URL: http://localhost:8080/api/v1
      STAGING_URL: http://localhost:3000
    ports:
      - "8091:8080"
    volumes:
      - .:/app
      - /app/node_modules
    # environment:
    #   NODE_ENV: developmentdoc
    networks:
      - supspace-network
    depends_on:
      - mongodb
  
  mongodb:
      container_name: mongo_supspace
      image: mongo:4.4.17-focal
      restart: always
      ports:
        - "27018:27017"
      volumes:
        - ./mongo-data:/data/db
      networks:
        - supspace-network
      environment:
        MONGO_INITDB_ROOT_USERNAME: mongo
        MONGO_INITDB_ROOT_PASSWORD: supspace1
        MONGO_URI: mongodb://mongo:supspace1@localhost:27017/
      # profiles: ["app","dev"]
      logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "10m"
  mongo-express:
      image: mongo-express:0.54.0
      container_name: mongo-express_supspace
      restart: always
      ports:
        - 8081:8081
      networks:
        - supspace-network
      environment:
        # ME_CONFIG_BASICAUTH_USERNAME: "mongo"
        # ME_CONFIG_BASICAUTH_PASSWORD: "supspace1"
        ME_CONFIG_SITE_BASEURL: "/mongodb/"
        ME_CONFIG_MONGODB_URL: "mongodb://mongo:supspace1@mongo:27017/"
        # ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
        # - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
        # - ME_CONFIG_MONGODB_ADMINPASSWORD=supspace1
        ME_CONFIG_MONGODB_SERVER: "mongodb"
        ME_CONFIG_MONGODB_ADMINUSERNAME: "mongo"
        ME_CONFIG_MONGODB_ADMINPASSWORD: "supspace1"
      depends_on:
        - mongodb
      # profiles: ["app","dev"]
      logging:
        driver: "json-file"
        options:
          max-file: "5"
          max-size: "10m"
networks:
      supspace-network:
        driver: bridge
