version: "3.1"

services:
  supspace-client:
    image: edamh158/supspace-client:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    stdin_open: true

  nginx: 
    image: edamh158/supspace-nginx:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "80:80"
    depends_on:
      - supspace-client

  supspace-api:
    image: edamh158/supspace-api:latest
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
    ports:
      - "8090:8080"
    environment:
      MONGODB_URI: mongodb://mongo:supspace1@mongodb:27017/
      MONGODB_DB_NAME: supspace-api-prod
      JWT_SECRET: edam1234
      JWT_EXPIRE: 30d
      SMTP_USERNAME: supchat24@outlook.com
      SMTP_PASSWORD: cin11149398
      NODE_ENV: development
      GOOGLE_CLIENT_ID: smth.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: SMTH-SMTH
      CLIENT_URL: http://supspace-client:3000
      API_URL: http://localhost:8080/api/v1
    command: node dist/index.js

  mongodb:
    image: mongo:4.4.17-focal
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: supspace1
      MONGO_URI: mongodb://mongo:supspace1@localhost:27017/
    volumes:
      - db_prod:/data/db

volumes:
  db_prod: