# Build stage
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:18-alpine AS production

WORKDIR /app

RUN mkdir -p /dist

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=build /app/dist ./dist

# COPY --from=build /app/.env ./

EXPOSE 8080

CMD [ "node", "dist/index.js" ]