global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: "my-project"

scrape_configs:
  - job_name: "MERN_APP"
    scrape_interval: 5s
    static_configs:
      - targets: ["prod_supspace-api:8080"]

  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
